version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: store
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL/db.sql:/docker-entrypoint-initdb.d/db.sql