CREATE TABLE  Users(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NOT NULL 
);

CREATE TABLE Products(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
)